version: '3.7'

services:
    web_app:
        container_name: web_app
        build:
            context: .
            dockerfile: Dockerfile
        networks: 
            - rosnet
        tty: true
        ports:
        - 3001:3000
        environment:
        - CHOKIDAR_USEPOLLING=true

networks:
    rosnet:
        driver: bridge